name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          pip install -r requirements.txt
          cd Scripts
          python RandomForestModel.py
          cd ..
          cat RF_metrics.txt >> report.md
          cml-send-comment report.md
