name: model-sales
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          cd Scripts
          python RF_model.py
          
          echo "## Model metrics" > report.md
          cat RF_metrics.txt >> report.md        
          cml-send-comment report.md
         
